# Generated by Django 5.1.2 on 2025-10-24 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_full_name_profile_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='preferred_mode',
            field=models.CharField(blank=True, help_text='e.g., Online / Offline / Hybrid', max_length=200),
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('location', models.CharField(blank=True, max_length=150)),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
                ('salary_range', models.CharField(blank=True, max_length=100)),
                ('job_type', models.CharField(blank=True, help_text='e.g., Full-time / Part-time / Freelance', max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
