# Generated by Django 5.2.7 on 2025-10-25 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_preferred_mode_jobpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='availability',
            field=models.CharField(choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day'), ('Evening Hours', 'Evening Hours')], default='Full Day', max_length=50),
        ),
    ]
