# Generated by Django 5.2.7 on 2025-11-25 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_profile_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='company_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
