# Generated by Django 5.2.7 on 2025-12-11 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_profile_company_name_profile_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='gst_number',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
